### ISSUE TITLE
Test KanBan Board 

### ISSUE THREAD

**Issue by Rickey-McCalop** [bethel-school-of-technology/bethel-bakery-backend#2]
Testing to see if Card is added to Bethel-Bakery
- [ ] dash/ bracket makes a checkbox

**Comment by slugguts** [comment]
Yup!
    On Thursday, November 4, 2021, 7:19:31 PM PDT, Rickey-McCalop ***@***.***> wrote:  
 
 


Testing to see if Card is added to Bethel-Bakery

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by slugguts** [comment]
I don't think it added a card.

**Comment by Rickey-McCalop** [comment]
No it Didn't. I have all the cards updated on the Trello board. I used the MVC Document to populate the board. I will try and add detail to the cards by tomorrow so when we start coding we can just get right to it.

**Comment by slugguts** [comment]
I think this issue was resolved, correct?

**Comment by slugguts** [comment]
Maybe this issue wasn't resolved...
